test('our first test', () => {
  throw new Error('Something failed');
});
